//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTest_EmtityFram_WPF
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Vendors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendors()
        {
            this.Products = new ObservableCollection<Products>();
        }
    
        public string vend_id { get; set; }
        public string vend_name { get; set; }
        public string vend_address { get; set; }
        public string vend_city { get; set; }
        public string vend_state { get; set; }
        public string vend_zip { get; set; }
        public string vend_country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Products> Products { get; set; }
       
    }
}
