//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTest_WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int order_num { get; set; }
        public int order_item { get; set; }
        public string prod_id { get; set; }
        public int quantity { get; set; }
        public decimal item_price { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
